#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build K1s from Yh793 repo

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Build Padavan"
        required: true
        default: "build"
      busyboxver:
        type: choice
        description: 'busybox''s version'
        options:
        - 1.24.x
        - 1.34.1
        default: '1.24.x'
      theme:
        type: boolean
        description: '是否替换主题文件'
        default: 'false'
      wifi:
        type: boolean
        description: '是否替换wifi文件'
        default: 'false'

#设置仓库的读写权限
permissions:
  contents: write

env:
  REPOSITORY_URL: https://github.com/Yh793/rt-n56u.git
  TOOLCHAIN_URL: https://github.com/Yh793/Padavan-build/raw/master/mipsel-linux-uclibc.tar.xz
  WORK_PATH: /opt/rt-n56u
  TNAME: PSG1208s
  
jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@master
        env:
          token: ${{ secrets.R_TOKEN }}
      - name: Initialization environment
        run: |
          sudo apt-get update
          sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
          cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man \
          pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
          
      - name: Clone source code
        run: |
          git clone -b chongshengB --depth=1 $REPOSITORY_URL $WORK_PATH
          cd /$WORK_PATH/toolchain-mipsel
          #sh dl_toolchain.sh
          curl -O -L  $TOOLCHAIN_URL
          mkdir -p toolchain-3.4.x
          tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x
          mkdir -p /opt/images/

      - name: newly build boards
        run: |
          cd $WORK_PATH/trunk/configs/boards
          mkdir $TNAME
        
      - name: Recovery Padavan files download from remote
        run: |
          cp -rf Padavan/busybox-1.24.x $WORK_PATH/trunk/user
      - name: Recovery bin files download from remote
        run: |
          cp -f $TNAME/$TNAME.config $WORK_PATH/trunk/configs/templates/$TNAME.config
          cp -f $TNAME/board.h $WORK_PATH/trunk/configs/boards/$TNAME/board.h
          cp -f $TNAME/board.mk $WORK_PATH/trunk/configs/boards/$TNAME/board.mk
          cp -f $TNAME/kernel-3.4.x.config $WORK_PATH/trunk/configs/boards/$TNAME/kernel-3.4.x.config
          #cd $WORK_PATH/trunk/tools
          #sed -i "s#1.15.2#1.21.1#g" ./Makefile
          #sed -i "s#https://gomirrors.org/dl/go#https://dl.google.com/go#g" ./Makefile
          echo "复制配置文件结束"  
      - name: Recovery theme files download from remote
        if: github.event.inputs.theme == 'true'
        run: |
          sudo rm -rf $WORK_PATH/trunk/user/www/n56u_ribbon_fixed/bootstrap
          sudo rm -rf $WORK_PATH/trunk/user/www/n56u_ribbon_fixed/images
          cp -rf theme/. $WORK_PATH/trunk/user/www/n56u_ribbon_fixed
          echo "复制主题文件结束"  
      - name: Recovery wifi files download from remote
        if: github.event.inputs.wifi == 'true'
        run: |
          sudo rm -rf $WORK_PATH/trunk/proprietary
          cp -rf wifi/. $WORK_PATH/trunk

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YY.MMDDHH
          utcOffset: "+08:00"

      - name: Build Firmware
        run: |
          cd $WORK_PATH/trunk
          if [ ! -f configs/templates/$TNAME.config ] ; then
          echo "configs/templates/$TNAME.config not found "
          exit 1
          fi
          cp -f configs/templates/$TNAME.config .config
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
          ################################################################################################
          #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
          ################################################################################################
          sed -i '/CONFIG_FIRMWARE_WIFI2_DRIVER=3.0/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config #删除配置项SOFTETHERVPN
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config #删除配置项SOFTETHERVPN
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config #删除配置项SOFTETHERVPN        
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项SS plus+
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #删除配置项SS server
          sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项DNSFORWARDER
          sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #删除配置项adbyby plus+
          sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #删除配置项adbyby plus+
          sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #删除配置项adbyby plus+
          sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #删除配置项adbyby plus+
          sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #删除配置项阿里DDNS
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_KUMASOCKS/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_IPT2SOCKS/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_MICROSOCKS/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SFE/d' .config #删除配置项SFE加速
          #校园网相关
          sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项MENTOHUST
          sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #删除配置项SCUTCLIENT
          sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_TTYD/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_NANO/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_HTOP/d' .config
          sed -i '/CONFIG_FIRMWARE_INCLUDE_MTR/d' .config
          #校园网相关
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
          ######################################################################
          #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
          ######################################################################        
          #2.4G 驱动选择
          ### 2.7 = MT7620 v2.7.2.0
          ### 3.0 = MT7620 v3.0.4.0
          echo "CONFIG_FIRMWARE_WIFI2_DRIVER=3.0" >> .config
          #
          echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> .config #SOFTETHERVPN
          echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> .config #SOFTETHERVPN
          echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> .config #SOFTETHERVPN
          echo "CONFIG_FIRMWARE_INCLUDE_SFE=n" >> .config #集成SFE加速
          #
          echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config #SS plus+
          echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #集成v2ray执行文件（3.8M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
          echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #集成trojan执行文件(1.1M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
          echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config # simple-obfs混淆插件
          echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
          echo "CONFIG_FIRMWARE_INCLUDE_KUMASOCKS=n" >> .config #socks5
          #
          echo "CONFIG_FIRMWARE_INCLUDE_IPT2SOCKS=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_MICROSOCKS=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #可以不集成
          echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
          echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
          #
          echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config #内网穿透FRPC
          echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #内网穿透FRPS
          #
          echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config #adbyby plus+
          echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KP广告过滤
          #
          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config #smartdns
          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config #smartdns二进制文件
          echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config
          #
          echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #阿里DDNS
          echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
          #       
          echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #在线文件管理服务
          echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #集成caddu执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用
          #     
          echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #网易云解锁
          echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #网易云解锁GO版本执行文件（4M多）注意固件超大小,不集成会自动下载
          #校园网相关
          echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
          echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
          echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_TTYD=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_NANO=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_HTOP=n" >> .config
          echo "CONFIG_FIRMWARE_INCLUDE_MTR=n" >> .config
          #校园网相关
          #########################################################################################
          #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
          #格式如下：
          #sed -i '/自定义项/d' .config
          #echo "自定义项=y" >> .config
          #########################################################################################
          sudo ./clear_tree
          sudo ./build_firmware_modify $TNAME 0
          sudo mv -f images/*.trx /opt/images/${TNAME}_ChongshengB_${{ steps.current-time.outputs.formattedTime }}.trx
          cp -f .config /opt/images/${TNAME}.config
          echo "FNAME=$TNAME" >> $GITHUB_ENV
          echo "BUILDDONE=success" >> $GITHUB_ENV
          
      - name: Upload packages - push to artifact file
        uses: actions/upload-artifact@main
        if: env.BUILDDONE == 'success'
        with:
          name: Yh793_K1s-Padavan-packages
          path: /opt/images
